name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  mix_test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: "1.11.4"
              otp: "22.x"
          - pair:
              elixir: "1.15.1"
              otp: "25.x"
            lint: lint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: deps
          key: deps-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: deps-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-
      - uses: actions/cache@v3
        with:
          path: _build
          key: build-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: build-${{ runner.os }}-${{ matrix.pair.otp }}-${{ matrix.pair.elixir }}-
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - name: Install Dependencies
        run: mix deps.get

      - run: mix format --check-formatted
        if: ${{ matrix.lint }}

      - run: mix deps.unlock --check-unused
        if: ${{ matrix.lint }}

      - run: mix deps.compile

      - run: mix compile --warnings-as-errors
        if: ${{ matrix.lint }}

      - name: Run Credo
        run: mix credo
        if: ${{ matrix.lint }}

      - name: Run Tests
        run: mix test
        if: ${{ ! matrix.lint }}

      - name: Run Tests
        run: mix test --warnings-as-errors
        if: ${{ matrix.lint }}
